# Site settings
title: Phil's-osophy
email: philipdekock@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Another tech blog on random development developments and such...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.phils-osophy.co.za/" # the base hostname & protocol for your site
twitter_username: apdekock
github_username:  apdekock
# Build settings
markdown: kramdown
# highlighter: rouge